name: Test .NET
on:
  workflow_call:
    outputs:
      test_results:
        value: ${{ jobs.build.outputs.test_results }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Necessary for installing OpenSSL 1.1
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    outputs:
      test_results: net-test-results
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenSSL 1.1
        run: |
          wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            3
            5
            6
            7
            8
            9
            10

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage;Format=opencover" --results-directory TestResults --logger:"trx;LogFileName=TestResults.trx" --logger:"console;verbosity=normal"
      
      - name: Upload test results
        id: upload_test_results
        uses: actions/upload-artifact@v4
        with:
          name: net-test-results
          path: TestResults
